-- =========================================================================
-- HR Team Tracker · Esquema Supabase
-- Ejecutar en Supabase → SQL Editor. Crea tablas y RLS de solo lectura pública.
-- =========================================================================

create table if not exists public.staff (
  id             bigint generated by default as identity primary key,
  nombre         text        not null,
  employee_id    text,
  is_contractor  boolean     default false,
  rol            text,
  seniority      text,
  is_lider       boolean     default false,
  skills         jsonb       default '{}'::jsonb,
  created_at     timestamptz default now()
);

create table if not exists public.proyectos (
  id         text primary key,          -- ej. "PJ-8012561"
  nombre     text not null,
  tipo       text,
  inicio     date,
  fin        date,
  recursos   jsonb default '[]'::jsonb, -- [{rol,nombre,hs}, ...]
  created_at timestamptz default now()
);

create table if not exists public.mantenimientos (
  id         text primary key,
  nombre     text not null,
  tipo       text,
  fin        date,
  lider      text,
  hs         numeric default 0,
  created_at timestamptz default now()
);

-- =========================================================================
-- Row-Level Security (RLS): lectura pública, escritura solo autenticados
-- =========================================================================
alter table public.staff          enable row level security;
alter table public.proyectos      enable row level security;
alter table public.mantenimientos enable row level security;

-- SELECT público (para que la app estática con anon key pueda leer)
create policy "public read staff"          on public.staff          for select using (true);
create policy "public read proyectos"      on public.proyectos      for select using (true);
create policy "public read mantenimientos" on public.mantenimientos for select using (true);

-- INSERT/UPDATE/DELETE solo usuarios autenticados (opcional; ajústelo a su caso)
create policy "auth write staff"          on public.staff          for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "auth write proyectos"      on public.proyectos      for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "auth write mantenimientos" on public.mantenimientos for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
